### ISSUE TITLE
sign in rodrigues formula

### ISSUE THREAD

**Issue by liren-jin** [Abekabe/IMU-Dead-Reckoning#3]
https://github.com/Abekabe/IMU-Dead-Reckoning/blob/b4ca3ce3e26400913e8509dd913a4cf2b1ada70c/src/Imu_Integrator/src/Imu_Integrator.cpp#L70

Hey, why is here minus?

**Comment by Abekabe** [comment]
I think it's a coding sytle issue.
We want to minus ((1 - std::cos(sigma)) / std::pow(sigma, 2)) * B * B) in the coefficient of orientation.

**Comment by Abekabe** [comment]
Yes, you're right.
It should be plus here.

**Comment by Abekabe** [comment]
The fix is merged.
Thanks for raising this issue!
